update

diff --git a/bin/orcl_resetpw b/bin/orcl_resetpw
--- a/bin/orcl_resetpw
+++ b/bin/orcl_resetpw
@@ -1,6 +1,6 @@
 #!/bin/bash
 # set -x
-# INCOMPLETE!!!
+# Author: Adam Richards
 ####################################
 # get script directory
 SWD=$(dirname ${0})
@@ -23,6 +23,7 @@ OPTIONS:
 -m value  host
 -s value  sid
 -u value  username
+-f        pwfile
 -a        reset all 
 -v        verbose
 EOF
@@ -38,7 +39,7 @@ PWFILE=
 ####################################
 # process command line arguments
 # options with : after them expect an argument
-while getopts “hm:s:u:av” OPTION
+while getopts “hm:s:u:f:av” OPTION
 do
      case $OPTION in
 	 h)
@@ -54,6 +55,9 @@ do
 	 s)
 	     SID=$OPTARG
 	     ;;
+	 f)
+	     PWFILE=$OPTARG
+	     ;;
 	 a)
 	     A=1
 	     ;;
@@ -68,24 +72,25 @@ do
 done
 ####################################
 # validate arguments
-if [[ -z $HOSTFILE ]] 
-then
+# minimus HOST or A (for all )
+if [[ -z $HOST ]] && [[ $A -eq 0 ]];then
      usage
      exit 1
 fi
 
-if [[ -z $SQLFILE ]] 
-then
-     usage
-     exit 1
+# pwfile required and valid
+if [[ -z $PWFILE ]] ;then
+	usage
+	exit 1
+else
+	if [[ ! -f "${PWFILE}" ]]; then
+	    printf "File not found: %s\n" "${PWFILE}"
+	    exit 1
+	fi
 fi
 
-if [[ ! -f "${SQLFILE}" ]]; then
-    printf "File not found: %s\n" "${SQLFILE}"
-    exit 1
-fi
 
-####################################
+# ssh
 assertIdentityFile
 ####################################
 # generate unique timestamp
@@ -98,50 +103,64 @@ TFILE="${TFILE/__TS__/$TS}"
 TFILE2="/tmp/tmp2___TS__.txt"
 TFILE2="${TFILE2/__TS__/$TS}"
 ####################################
-# if hostfile variable is a file we
-# will read it for host info
-if [[ -f "${HOSTFILE}" ]]; then
-HOSTLIST=$(collectHostsFromFile "$HOSTFILE")
-else
-# the hostfile variable is a single hostname
-HOSTLIST="${HOSTFILE}"
-fi
-
-for HOST in ${HOSTLIST}; do
-if [[ $SID = 0 ]]; then
-SIDLIST=$(orcl_getsids $HOST)
-else
-# user specified a single sid
-SIDLIST="$SID"
-fi
-
-
-for w in ${SIDLIST}; do 
-cat /dev/null > "${TFILE}"
-if [[ $V = 1 ]]; then
-printf "Processing on %s %s:\n" "${HOST}" "${w}" 
-printf ">> %s %s:\n" "${HOST}" "${w}" >> "${TFILE}"
-fi
-cat "${SQLFILE}" | ssh -T -q -i "${ORCL_SSHIDFILE}" -t "${ORCL_SSHUSER}"@$HOST "export ORACLE_SID=$w;export ORAENV_ASK=NO;. oraenv >/dev/null;sqlplus -S '/ as sysdba' " >>  ${TFILE} 
+function resetPW()
+{
+SQL='alterr user ${USERNAME} identified by "${PW}" account unlock'
+# substitue
+TSQL=$(echo "${SQL}" | perl -p -e "s/\\$\{USERNAME\}/${3}/g")
+TSQL=$(echo "${TSQL}" | perl -p -e "s/\\$\{PW\}/${4}/g")
+# run it
+printf "%s\n" "${TSQL}" | ssh -T -q -i "${ORCL_SSHIDFILE}" -t "${ORCL_SSHUSER}"@$1 "export ORACLE_SID=$2;export ORAENV_ASK=NO;. oraenv >/dev/null;sqlplus -S '/ as sysdba' " >  ${TFILE} 
 
 # check for errors
-grep -q -i -e "^ORA-" "${TFILE}"
+grep -q -i -e "^ORA-\|^SP2-" "${TFILE}"
 OK=$?
-if [[ $OK -eq 0 ]]; then
-printf ">> %s %s:\n" "${HOST}" "${w}" 
-grep -i -e "^ORA-" "${TFILE}"
-echo "$HOST $w Query Failed" >> ${FINAL}
+if [[  $OK -eq 0 ]]; then
+printf ">> %s %s:\n" "${1}" "${2}" 
+grep -i -e "^ORA-\|^SP2-" "${TFILE}"
+echo "$1 $2 Query Failed" >> ${FINAL}
 else
 cat ${TFILE} >> ${FINAL}
 fi
-done
+}
+####################################
+# look through pwfile
+IFS_ORIG=$IFS
+IFS=$'\r\n' RECORDS_ARRAY=($(cat "${PWFILE}"))
 
+for RECORD in "${RECORDS_ARRAY[@]}" ; do
+#ignore comment lines
+COMMENT_REGEX='^\s*#'
+if [[ ${RECORD} =~ $COMMENT_REGEX ]]; then
+continue
+fi
+IFS='|' read -ra RECORD_ARRAY <<< "${RECORD}"
+H=$(printf "%s" "${RECORD}" | cut -d'|' -f1 )
+S=$(printf "%s" "${RECORD}" | cut -d'|' -f2 )
+UN=$(printf "%s" "${RECORD}" | cut -d'|' -f3 )
+PW=$(printf "%s" "${RECORD}" | cut -d'|' -f4 )
+# if processin ALL
+if [[ $A -eq 1 ]]; then
+	printf "Processing %s %s %s \n" "${H}" "${S}" "${UN}" 
+	resetPW "${H}" "${S}" "${UN}" "${PW}"
+else
+	if [[ ! -z $HOST ]] && [[ $A -eq 0 ]] && [[ -z $SID ]]; then
+	fi
+fi
 done
+IFS=$IFS_ORIG
+###################################
+# check identity file for non interactive 
 
+####################################
+# cleanup and display output of all steps
+if [[ -f "${FINAL}" ]]; then
 cp ${FINAL} ${TFILE2}
 cat ${TFILE2} | perl -e 'while (<>) {$_=~s/[ \t]+$//g;print;}' > $FINAL
 cat ${FINAL}
+fi
+####################################
 # cleanup
-rm /tmp/*${TS}*
+rm /tmp/*${TS}* 2> /dev/null
 exit 0
 ##############################################
