added feedback

diff --git a/bin/orcl_resetpw b/bin/orcl_resetpw
--- a/bin/orcl_resetpw
+++ b/bin/orcl_resetpw
@@ -4,6 +4,7 @@
 ####################################
 # get script directory
 SWD=$(dirname ${0})
+IFS_ORIG=$IFS
 ###################################
 # load support files
 source "${SWD}/../config/orcl_config"
@@ -102,42 +103,53 @@ TFILE="/tmp/tmp___TS__.txt"
 TFILE="${TFILE/__TS__/$TS}"
 TFILE2="/tmp/tmp2___TS__.txt"
 TFILE2="${TFILE2/__TS__/$TS}"
-####################################
+########################################################################
 function resetPW()
 {
-SQL='alterr user ${USERNAME} identified by "${PW}" account unlock'
+read -r -d '' SQL <<'EOT'
+alter user ${USERNAME} identified by "${PW}" account unlock
+;
+
+EOT
 # substitue
 TSQL=$(echo "${SQL}" | perl -p -e "s/\\$\{USERNAME\}/${3}/g")
 TSQL=$(echo "${TSQL}" | perl -p -e "s/\\$\{PW\}/${4}/g")
 # run it
 printf "%s\n" "${TSQL}" | ssh -T -q -i "${ORCL_SSHIDFILE}" -t "${ORCL_SSHUSER}"@$1 "export ORACLE_SID=$2;export ORAENV_ASK=NO;. oraenv >/dev/null;sqlplus -S '/ as sysdba' " >  ${TFILE} 
 
+printf "Reset password: %s %s %s \n" "${1}" "${2}" "${3}" >> ${FINAL}
 # check for errors
 grep -q -i -e "^ORA-\|^SP2-" "${TFILE}"
 OK=$?
-if [[  $OK -eq 0 ]]; then
+if [[ $OK -eq 0 ]]; then
 printf ">> %s %s:\n" "${1}" "${2}" 
 grep -i -e "^ORA-\|^SP2-" "${TFILE}"
-echo "$1 $2 Query Failed" >> ${FINAL}
+printf "Failed\n" >> ${FINAL}
 else
 cat ${TFILE} >> ${FINAL}
 fi
 }
+########################################################################
 function processRequest()
 {
-CLIST=0
-CEXE=0
-if [[ "${1}" = "list" ]]; then
-CLIST=1
-fi
-if [[ "${1}" = "execute" ]]; then
-CEXE=1
-fi
-####################################
-# look through pwfile
-IFS_ORIG=$IFS
+OP="${1}"
+case "${OP}" in
+"list")
+;;
+"execute")
+;;
+*)
+printf "Invalid op \"%s\".\n" "${OP}"
+OK=1
+return 1
+;;
+esac
+
 IFS=$'\r\n' RECORDS_ARRAY=($(cat "${PWFILE}"))
 
+if [[ "${OP}" = "list" ]]; then
+	printf "The following operations match selected criteria.\n"
+fi
 for RECORD in "${RECORDS_ARRAY[@]}" ; do
 #ignore comment lines
 COMMENT_REGEX='^\s*#'
@@ -156,35 +168,60 @@ UN=$(printf "%s" "${UN}" | sed -e 's/^ *//' -e 's/ *$//')
 PW=$(printf "%s" "${PW}" | sed -e 's/^ *//' -e 's/ *$//')
 # if processin ALL
 if [[ $A -eq 1 ]]; then
-	printf "Processing %s %s %s \n" "${H}" "${S}" "${UN}" 
+	if [[ "${OP}" = "list" ]]; then
+		printf "match: %s %s %s \n" "${H}" "${S}" "${UN}" 
+	fi
+	if [[ "${OP}" = "execute" ]]; then
 	resetPW "${H}" "${S}" "${UN}" "${PW}"
+	fi
 else
 	if [[ ! -z $HOST ]] && [[ -z $SID ]] && [[ -z $UNAME ]] && [[ $A -eq 0 ]] ; then
 		if [[ "${HOST}" = "${H}" ]]; then
-		printf "Processing %s %s %s \n" "${H}" "${S}" "${UN}" 
+			if [[ "${OP}" = "list" ]]; then
+				printf "match: %s %s %s \n" "${H}" "${S}" "${UN}" 
+			fi
+			if [[ "${OP}" = "execute" ]]; then
+				printf "Processing %s %s %s \n" "${H}" "${S}" "${UN}" 
+				resetPW "${H}" "${S}" "${UN}" "${PW}"
+			fi
 		fi
 	fi
 	if [[ ! -z $HOST ]] && [[ ! -z $SID ]] && [[ -z $UNAME ]] && [[ $A -eq 0 ]] ; then
 		if [[ "${HOST}" = "${H}" ]] && [[ "${SID}" = "${S}" ]]; then
-		printf "Processing %s %s %s \n" "${H}" "${S}" "${UN}" 
+			if [[ "${OP}" = "list" ]]; then
+				printf "match: %s %s %s \n" "${H}" "${S}" "${UN}" 
+			fi
+			if [[ "${OP}" = "execute" ]]; then
+				printf "Processing %s %s %s \n" "${H}" "${S}" "${UN}" 
+				resetPW "${H}" "${S}" "${UN}" "${PW}"
+			fi
 		fi
 	fi
 	if [[ ! -z $HOST ]] && [[ ! -z $SID ]] && [[ ! -z $UNAME ]] && [[ $A -eq 0 ]] ; then
 		if [[ "${HOST}" = "${H}" ]] && [[ "${SID}" = "${S}" ]] && [[ "${UNAME}" = "${UN}" ]]; then
-		printf "Processing %s %s %s \n" "${H}" "${S}" "${UN}" 
+			if [[ "${OP}" = "list" ]]; then
+				printf "match: %s %s %s \n" "${H}" "${S}" "${UN}" 
+			fi
+			if [[ "${OP}" = "execute" ]]; then
+				printf "Processing %s %s %s \n" "${H}" "${S}" "${UN}" 
+				resetPW "${H}" "${S}" "${UN}" "${PW}"
+			fi
 		fi
 	fi
 fi
 done
-IFS=$IFS_ORIG
 }
-####################################
+IFS=$IFS_ORIG
+########################################################################
 processRequest "list"
-read -p "execute update?enter "yes" to proceed, return to abort: " r 
+if [[ $OK -ne 0 ]]; then
+	exit 1
+fi
+read -p "Execute update? Enter "yes" to proceed, return to abort: " r 
 if [[ "${r}" = "yes" ]]; then
 	processRequest "execute"
 else
-	printf "\nUser aborted\n"
+	printf "\nUser aborted operation.\n"
 	exit 1
 fi
 ####################################
@@ -198,4 +235,4 @@ fi
 # cleanup
 rm /tmp/*${TS}* 2> /dev/null
 exit 0
-##############################################
+########################################################################
